stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - params.yaml
    - src/data/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - params.yaml
    - src/data/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - params.yaml
    - src/features/feature_engineering.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - params.yaml
    - src/model/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    #- data/processed
    - models/model.pkl
    #- params.yaml
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
